version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: docker.io/library/postgres:16-alpine
    container_name: mirror-postgres
    restart: always
    env_file:
      - ./mirror-database/.env
    volumes:
      - ./mirror-database/postgres_data:/var/lib/postgresql/data:Z
    networks:
      - mirror-network
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USERNAME} -d ${PG_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5


  # Beatmap Fetcher Service
  beatmap-fetcher:
    build:
      context: ./beatmap-fetcher
      dockerfile: Dockerfile
    container_name: beatmap-fetcher
    restart: always
    env_file:
      - ./beatmap-fetcher/src/.env.production
    volumes:
      - ./mirror-storage/storage:/app/storage:Z
      - osu-cookies:/app/src/cookies:Z
    networks:
      - mirror-network
    depends_on:
      postgres:
        condition: service_healthy
      cookie-fetcher:
        condition: service_started
    security_opt:
      - label=disable

  # Cookie Fetcher Service
  cookie-fetcher:
    build:
      context: ./cookie-fetcher
      dockerfile: Dockerfile
    container_name: cookie-fetcher
    restart: always
    volumes:
      - osu-cookies:/app/cookies:Z
      - ./cookie-fetcher/puppeteer_profile:/app/puppeteer_profile:Z
    networks:
      - mirror-network
    security_opt:
      - label=disable

  # Mirror API Server
  mirror-server:
    build:
      context: ./mirror-server
      dockerfile: Dockerfile
    container_name: mirror-server
    restart: always
    env_file:
      - ./mirror-server/src/.env
    ports:
      - "30727:30727"
    volumes:
      - /run/user/${UID:-1000}/podman/podman.sock:/run/podman/podman.sock:ro
      - ./mirror-storage/storage:/app/storage:Z
    networks:
      - mirror-network
    extra_hosts:
      - "host.containers.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
    security_opt:
      - label=disable

  # Portainer
  portainer:
    image: docker.io/portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - /run/user/${UID:-1000}/podman/podman.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - mirror-network


  # Prometheus - Metrics Storage
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    restart: always
    network_mode: host
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'

  # Grafana - Visualization
  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./monitoring/grafana.ini:/etc/grafana/grafana.ini:ro
    networks:
      - mirror-network
    extra_hosts:
      - "host.containers.internal:host-gateway"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_COOKIE_SAMESITE=none
      - GF_SECURITY_COOKIE_SECURE=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - allow_embedding=true
    depends_on:
      - prometheus

  # valkey
  valkey:
    image: docker.io/valkey/valkey:9.0
    container_name: valkey
    restart: always
    networks:
      - mirror-network
    ports:
      - "127.0.0.1:6380:6379"
    volumes:
      - valkey_data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ############
  # EXPORTER #
  ############

  # NOTE: podman-exporter cannot be started via podman-compose
  # Reason: --userns=keep-id conflicts with podman-compose's pod usage
  # Start it manually with:
  # podman run -d --name podman-exporter --restart=always --network=host \
  #   -v /run/user/1000/podman/podman.sock:/run/podman/podman.sock:ro \
  #   -e CONTAINER_HOST=unix:///run/podman/podman.sock \
  #   --userns=keep-id quay.io/navidys/prometheus-podman-exporter:latest

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    restart: always
    networks:
      - mirror-network
    ports:
      - "9187:9187"
    env_file:
      - ./mirror-database/.env
    environment:
      - DATA_SOURCE_NAME=postgresql://${PG_USERNAME}:${PG_PASSWORD}@mirror-postgres:5432/${PG_DATABASE}?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

  redis-exporter:
    image: docker.io/oliver006/redis_exporter:latest
    container_name: redis-exporter
    restart: always
    networks:
      - mirror-network
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=valkey:6379
    depends_on:
      - valkey

  # FTP Server (read-only + write user)
  sftp-server:
    image: docker.io/atmoz/sftp
    container_name: sftp-server
    restart: always
    volumes:
      # Shared directory on the host
      - ./mirror-storage/storage:/home/public/storage:ro
      - ./mirror-storage/storage:/home/railgun/storage
      # Users configuration
      - ./users.conf:/etc/sftp/users.conf:ro
      # Persistent SSH keys
      - ./sftp-keys/sftp-keys:/etc/ssh:Z
    ports:
      - "2222:22"

networks:
  mirror-network:
    external: true

volumes:
  osu-cookies:
    external: true
  portainer_data:
    external: true
  prometheus_data:
  grafana_data:
  valkey_data:
